### ISSUE TITLE
BOSH Google CPI error with `snapshot_disk` and payload unmarshalling

### ISSUE THREAD

**Issue by RochesterinNYC** [cloudfoundry-incubator/bosh-google-cpi-release#126]
```
$ bosh restart db/0 --force
Restart db/*? (type 'yes' to continue): yes

Performing 'restart db/*'...

Director task 256
  Started preparing deployment > Preparing deployment. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started updating instance db > db/<instance_guid> (0) (canary). Failed: CPI error 'Bosh::Clouds::CloudError' with message 'Extracting method arguments from payload: Unmarshalling action argument: json: cannot unmarshal number into Go value of type string' in 'snapshot_disk' CPI method (00:00:02)

Error 100: CPI error 'Bosh::Clouds::CloudError' with message 'Extracting method arguments from payload: Unmarshalling action argument: json: cannot unmarshal number into Go value of type string' in 'snapshot_disk' CPI method

Task 256 error
```

BOSH manifest for Concourse:

```yaml
---
name: concourse
director_uuid: <director uuid>
releases:
- name: concourse
  version: 2.5.0
  url: https://bosh.io/d/github.com/concourse/concourse?v=2.5.0
  sha1: 0d1f436aad50bb09ac2c809cd6cb6df3e38a7767
- name: garden-runc
  version: 1.0.3
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.0.3
  sha1: 0c04b944d50ec778f5b34304fd4bc8fc0ed83b2b

tls_key: &tls_key |
  <tls key>
tls_cert: &tls_cert |
  <tls cert>

instance_groups:
- name: web
  instances: 1
  vm_type: web
  azs:
  - z1
  - z2
  stemcell: trusty
  networks:
  - name: public
    default:
    - dns
    - gateway
  - name: vip
    static_ips:
    - <static ip>
  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: <external url>
      publicly_viewable: true
      basic_auth_username: buildpacks
      basic_auth_password: "<auth password>"
      github_auth:
        client_id: <client id>
        client_secret: <client secret>
      postgresql_database: atc
      tls_cert: *tls_cert
      tls_key: *tls_key
      tls_bind_port: 443
  - name: tsa
    release: concourse
    properties: {}
- name: db
  instances: 1
  vm_type: database
  azs:
  - z1
  stemcell: trusty
  persistent_disk_type: database
  networks:
  - name: public
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: atc
        role: <role>
        password: <password>
- name: worker
  instances: 6
  vm_type: worker
  azs:
  - z1
  stemcell: trusty
  networks:
  - name: public
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        network_mtu: 1432
update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest
```

BOSH cloud config:

```yaml
azs:
- name: z1
  cloud_properties:
    zone: us-east1-c
- name: z2
  cloud_properties:
    zone: us-east1-d

vm_types:
- name: web
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

- name: database
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 100
    root_disk_type: pd-ssd

- name: worker
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 300
    root_disk_type: pd-ssd

- name: bosh-lite-worker
  cloud_properties:
    machine_type: n1-standard-16
    root_disk_size_gb: 300
    root_disk_type: pd-ssd
    tags: [bosh-lite-public]

compilation:
  workers: 3
  network: public
  reuse_compilation_vms: true
  az: z1
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
    preemptible: true

networks:
  - name: public
    type: manual
    subnets:
    - az: z1
      range: <ip range>
      gateway: <gateway>
      cloud_properties:
        network_name: concourse
        subnetwork_name: <subnetwork name>
        ephemeral_external_ip: true
        tags:
          - concourse-public
          - concourse-internal
    - az: z2
      range: <ip range>
      gateway: <gateway>
      cloud_properties:
        network_name: concourse
        subnetwork_name: <subnetwork name>
        ephemeral_external_ip: true
        tags:
          - concourse-public
          - concourse-internal

  - name: vip
    type: vip

disk_types:
- name: database
  disk_size: 100000 #mb
```

This is with BOSH Google CPI version `25.6.1`. We were able to deploy the db VM as part of the Concourse deployment using this CPI version. However, during a re-deploy of the Concourse deployment, this error showed up and the DB VM did not recreate and ended up stopped. Any attempts to `bosh recreate`, `bosh start`, `bosh restart` the DB VM result in this error message.
