### ISSUE TITLE
dynamic networks should fail fast if required properties are not present

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry-incubator/bosh-google-cpi-release#143]
For dynamic network configuration using bosh-init (or `bosh create-env`), we require `cloud_properties` and `dns` at the root, e.g.

```yaml
networks:
- name: default
  type: dynamic
  cloud_properties:
    network_name: ((network))
    subnetwork_name: ((subnetwork))
  dns: 8.8.8.8
```

However, if we forget these fields (for example if they are incorrectly nested under `subnets` which is ignored by bosh-init/`bosh create-env`) the CPI will not fail, but will instead create the VM somewhere else - some default network?

cc @cppforlife @jpalermo
