### ISSUE TITLE
Compilation VM IPs colliding

### ISSUE THREAD

**Issue by kkallday** [cloudfoundry-incubator/bosh-google-cpi-release#242]
HI,

While deploying a fresh CF, our deployment ran into an IP collision problem when compiling releases. Here is the BOSH output:
```
Task 59 | 21:29:40 | Preparing deployment: Preparing deployment (00:00:07)
Task 59 | 21:29:50 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 59 | 21:29:50 | Compiling packages: cf-cli/73ae3f68c036049f186a23c0bbfd105c51854484
Task 59 | 21:29:50 | Compiling packages: golang1.8.3-windows/d22a2c32604d84e59a29555f81206e48caf3695c17050eb89ce9dbc9d9d2b7cd
Task 59 | 21:29:50 | Compiling packages: hwc-buildpack-windows/6b7da0c4b578860437b28b97ca4e0e02666d9203
Task 59 | 21:29:50 | Compiling packages: 7zip/a836729ad83534cc22df09ef86b5bfa594600679cfc7d88643f14e490d1e8e92
Task 59 | 21:32:12 | Compiling packages: cf-cli/73ae3f68c036049f186a23c0bbfd105c51854484 (00:02:22)
                   L Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'VM failed to create: Google Operation 'operation-1510867917179-55e2059818878-700d5365-a627aaa4' finished with an error: IP '10.0.0.9' is already being used by another resource. 
' in 'create_vm' CPI method
Task 59 | 21:35:57 | Compiling packages: hwc-buildpack-windows/6b7da0c4b578860437b28b97ca4e0e02666d9203 (00:06:07)
Task 59 | 21:36:05 | Compiling packages: 7zip/a836729ad83534cc22df09ef86b5bfa594600679cfc7d88643f14e490d1e8e92 (00:06:15)
Task 59 | 21:37:36 | Compiling packages: golang1.8.3-windows/d22a2c32604d84e59a29555f81206e48caf3695c17050eb89ce9dbc9d9d2b7cd (00:07:46)
Task 59 | 21:38:24 | Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'VM failed to create: Google Operation 'operation-1510867917179-55e2059818878-700d5365-a627aaa4' finished with an error: IP '10.0.0.9' is already being used by another resource. 
' in 'create_vm' CPI method

Task 59 Started  Thu Nov 16 21:29:40 UTC 2017
Task 59 Finished Thu Nov 16 21:38:24 UTC 2017
Task 59 Duration 00:08:44
Task 59 error
```

Based on our cloud config, the director's network is set to manual IP allocation.
```
networks:
- name: some-subnet
  type: manual
  subnets:
  - netmask: 255.255.255.0
    dns:
    - 169.254.169.254
    gateway: 10.0.0.1
    range: 10.0.0.0/24
    cloud_properties:
      subnetwork_name: some-subnet
      network_name: some-network
      ephemeral_external_ip: true
```

It looks like what is supposed to happen is 4 VMs are created to compile releases and the director should allocate 4 IPs. In this case, the director stood up 4 VMs but 2 VMs were given the same IP. This seems like an IP allocation bug.

After deleting the stray compilation via in the GCP console, our deployment succeeded.

cc @michelleheh
