### ISSUE TITLE
I can't seem to get VMs to attach to an instance_group

### ISSUE THREAD

**Issue by dsboulder** [cloudfoundry-incubator/bosh-google-cpi-release#30]
I created a manifest using `instance_group: nginx` in the subnet `cloud_properties` section of my cloud config, but I don't see new instances being attached to that group.  Are you sure that's wired up correctly internally?

Additionally - it seems weird that ELBs can be attached using vm_types (or vm_extensions, which is even better), but on GCP I have to attach a load balancer to _every_ VM in the network.  It's very common that I'd declare only 1 or 2 large networks, and I don't want all those VMs to have load balancers.  Could we make google's `instance_group` a `cloud_property` to a BOSH job (now confusingly called BOSH instance groups)?

Here's what BOSH printed out when I did the deploy, so it clearly understood the change:

```
> bosh deploy --recreate

Detecting deployment changes
----------------------------
networks:
- name: private
  subnets:
  - range: 10.128.0.0/20
    cloud_properties:
      instance_group: nginx
```

Then it recreated the VM:

```
  Started updating job web_server > web_server/0 (18857c48-665f-4600-bd00-c9e6909d6c87) (canary). Done (00:04:51)
```

But that new web server isn't part of an instance group.  I used CPI version 21, director 257.3, and stemcell 3262.2.

Here's the full network section of my cloud_config:

```
networks:
- name: private
  type: manual
  subnets:
  - dns:
    - 169.254.169.254
    range: 10.128.0.0/20
    gateway: 10.128.0.1
    azs:
    - us-central1-a
    cloud_properties:
      network_name: cf
      instance_group: nginx
      tags:
      - cf-bosh
    reserved:
    - 10.128.0.2
    - 10.128.0.10-10.128.15.254
    static:
    - 10.128.0.8
```

Let me know if I just did something wrong.  Thanks!
