### ISSUE TITLE
Property names are different with the google CPI than others

### ISSUE THREAD

**Issue by dsboulder** [cloudfoundry-incubator/bosh-google-cpi-release#31]
Hey GCP CPI developers - 

I noticed some inconsistencies when using the google CPI next to the AWS, OpenStack, and vSphere CPIs.  There's a few properties that aren't named the same with the google CPI, here's what they are:

1.  The bosh-init cloud_provider `agent:` properties section seems to expect `blobstore` and `ntp` settings.  Usually these settings are at the root level and are pulled in by the other CPIs.

2.  The bosh-init job properties `agent` section has a similar inconsistency in it.  Usually the `blobstore` and `ntp` settings are not inside the agent section.

3.  The local bosh-init blobstore path in your CPI is provided in an additional namespace called `blobstore_options` like this: `{provider: "local", options: {blobstore_path: "/var/vcap/micro_bosh/data/cache"}}`.  Other CPIs have the blobstore path more at the root level like this: `{provider: "local", path: "/var/vcap/micro_bosh/data/cache"}`

If y'all help make those changes, it'll be much easier for existing BOSH users of another IaaS to learn GCP.  I've already had 5 or 6 people run into this, including me.  Thanks!!!

**Comment by evandbrown** [comment]
Howdy @dsboulder,

It was my understanding that the manifest parsing in `bosh-init` was handled was handled by `bosh-init`

**Comment by evandbrown** [comment]
Howdy @dsboulder,

It looks like the `bosh-init` manifest parsing is pretty loose when handling `cloud_provider.properties`: it [unmarshals `properties` to a map](https://github.com/cloudfoundry/bosh-init/blob/da7d81454c5170414bf517f9a4423918e3229a39/installation/manifest/parser.go#L86). I'm guessing that is plumbed into the CPI [here](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/src/bosh-google-cpi/registry/agent_settings.go#L11-L35), but I'm not seeing anything else in the CPI where we use `settings["blobstore_path"]` or similar. Are these values passed directly to the `bosh-agent`, and it's being flexible with the values it receives?

**Comment by dsboulder** [comment]
@evandbrown I think you're right about `blobstore_path`, that must have been a change to the director/agent that was totally unrelated to this particular CPI.  You okay making the other changes though?

**Comment by evandbrown** [comment]
@dsboulder Clarifying question: the `bosh-agent` uses the blobstore and ntp config (https://github.com/cloudfoundry/bosh-agent/blob/master/settings/settings.go), so it feels right that they're nested in the `agent` property. But then I see the [job spec](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/jobs/aws_cpi/spec) for the AWS CPI, and it has both a `agent.blobstore` as well as a top level `blobstore`. Is there a difference? Should we have both in the Google CPI?

It was easy to reorder the struct fields, and I think all that's left is the job spec's `cpi.json.erb`, I just want to be sure there wasn't a good reason for nesting this under `agent` in the first place. Thoughts?

**Comment by dsboulder** [comment]
@cpp4life what do you think?

**Comment by dsboulder** [comment]
@cppforlife for real.  Dmitriy might have a plan to normalize them better, I agree with you Eric that it makes sense under Agent, it's just not what the other ones do.

**Comment by ljfranklin** [comment]
@dsboulder @evandbrown The vSphere and AWS CPIs allow the user to specify blobstore + ntp either under `agent` or at the root. That said, when we actually generate the `cpi.json` file, we always nest these properties under `agent`. Agreed that it makes more sense to nest under `agent`, but all our bosh.io example bosh-init manifests show these props at the top level. Oh well, seems like allowing it in both places makes the most sense in practice.

**Comment by dsboulder** [comment]
Maybe then the best solution is to allow parameters to come in with either name.  What do you think @evandbrown?

**Comment by evandbrown** [comment]
@dsboulder totally agree. @ljfranklin's comment and a convo w/ Corrie today made things crystal clear. should have this working very shortly...

**Comment by evandbrown** [comment]
@dsboulder #37 (pending BATS and int tests) supports a template with `cloud_provider.properties` like this

```
  properties:
    google: *google_properties
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
```

Does this look correct?

Full template here:

```
---
name: bosh

releases:
  - name: bosh
    url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=256.2
    sha1: ff2f4e16e02f66b31c595196052a809100cfd5a8
  - name: bosh-google-cpi
    url: file:///home/evanbrown/dev/cloudfoundry/bosh-google-cpi-release/dev_releases/bosh-google-cpi/bosh-google-cpi-21+dev.10.tgz

resource_pools:
  - name: vms
    network: private
    stemcell:
      url: file://stemcell.tgz
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 40
      root_disk_type: pd-standard
      service_scopes:
        - compute
        - devstorage.full_control

disk_pools:
  - name: disks
    disk_size: 32_768
    cloud_properties:
      type: pd-standard

networks:
  - name: vip
    type: vip
  - name: private
    type: manual
    subnets:
    - range: 10.0.0.0/29
      gateway: 10.0.0.1
      static: [10.0.0.3-10.0.0.7]
      cloud_properties:
        network_name: cf
        subnetwork_name: bosh-us-east1
        ephemeral_external_ip: true
        tags:
          - bosh-internal

jobs:
  - name: bosh
    instances: 1

    templates:
      - name: nats
        release: bosh
      - name: postgres
        release: bosh
      - name: powerdns
        release: bosh
      - name: blobstore
        release: bosh
      - name: director
        release: bosh
      - name: health_monitor
        release: bosh
      - name: google_cpi
        release: bosh-google-cpi

    resource_pool: vms
    persistent_disk_pool: disks

    networks:
      - name: private
        static_ips: [10.0.0.6]
        default:
          - dns
          - gateway

    properties:
      nats:
        address: 127.0.0.1
        user: nats
        password: nats-password

      postgres: &db
        listen_address: 127.0.0.1
        host: 127.0.0.1
        user: postgres
        password: postgres-password
        database: bosh
        adapter: postgres

      dns:
        address: 10.0.0.6
        domain_name: microbosh
        db: *db
        recursor: 169.254.169.254

      blobstore:
        address: 10.0.0.6
        port: 25250
        provider: dav
        director:
          user: director
          password: director-password
        agent:
          user: agent
          password: agent-password

      director:
        address: 127.0.0.1
        name: micro-google
        db: *db
        cpi_job: google_cpi
        user_management:
          provider: local
          local:
            users:
              - name: admin
                password: admin
              - name: hm
                password: hm-password
      hm:
        director_account:
          user: hm
          password: hm-password
        resurrector_enabled: true

      google: &google_properties
        project: evandbrown17
        default_zone: us-east1

      agent:
        mbus: nats://nats:nats-password@10.0.0.6:4222

      ntp: &ntp
        - 169.254.169.254

cloud_provider:
  template:
    name: google_cpi
    release: bosh-google-cpi

  ssh_tunnel:
    host: 10.0.0.6
    port: 22
    user: bosh
    private_key: /home/evanbrown/.ssh/google_compute_engine

  mbus: https://mbus:mbus-password@10.0.0.6:6868

  properties:
    google: *google_properties
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
```
