### ISSUE TITLE
Can't seem to use S3 blobstore providers with google CPI

### ISSUE THREAD

**Issue by dsboulder** [cloudfoundry-incubator/bosh-google-cpi-release#68]
I'm trying to use the S3 blobstore with the google CPI, just like I can with other CPIs, and I think the blobstore options aren't being passed through.  I'm attempting to pass blobstore options that look like this:
```
properties:
    blobstore:
      provider: s3
      host: storage.googleapis.com
      s3_port: 443
      use_ssl: true
      bucket_name: dstevenson-bosh
      access_key_id: GOOGB4BAQE4743O4YSAS
      secret_access_key: not-telling-you
      s3_force_path_style: true
      s3_multipart_threshold: 1099511627776
      s3_signature_version: '2'
```

But I get the following error, probably from the code inside of `cpi.json.erb` in the CPI:

```
                Running command: 'ruby /home/tempest-web/.bosh_init/installations/52ec4231-444e-4e0e-5383-e34254e7bfd4/tmp/erb-renderer206693177/erb-render.rb /home/tempest-web/.bosh_init/installations/52ec4231-444e-4e0e-5383-e34254e7bfd4/tmp/erb-renderer206693177/erb-context.json /home/tempest-web/.bosh_init/installations/52ec4231-444e-4e0e-5383-e34254e7bfd4/tmp/bosh-init-release576250374/extracted_jobs/google_cpi/templates/config/cpi.json.erb /home/tempest-web/.bosh_init/installations/52ec4231-444e-4e0e-5383-e34254e7bfd4/tmp/rendered-jobs472416459/config/cpi.json', stdout: '', stderr: '/home/tempest-web/.bosh_init/installations/52ec4231-444e-4e0e-5383-e34254e7bfd4/tmp/erb-renderer206693177/erb-render.rb:189:in `rescue in render': Error filling in template '/home/tempest-web/.bosh_init/installations/52ec4231-444e-4e0e-5383-e34254e7bfd4/tmp/bosh-init-release576250374/extracted_jobs/google_cpi/templates/config/cpi.json.erb' for google_cpi/0 (line 52: #<TemplateEvaluationContext::UnknownProperty: Can't find property 'agent.blobstore.address', or 'blobstore.address'>) (RuntimeError)
```

Should we just be passing blobstore options directly through to the agent?  Supporting google cloud storage for BOSH would be very useful for us.
