### ISSUE TITLE
VMs do not start google-address-manager

### ISSUE THREAD

**Issue by vito** [cloudfoundry-incubator/bosh-google-cpi-release#95]
This prevents them from being registered with a load balancer.

```
root@74c4feff-fbe2-4454-86af-530ba4413127:~# ip route list table local
local 10.1.0.4 dev eth0  proto kernel  scope host  src 10.1.0.4
broadcast 10.1.0.4 dev eth0  proto kernel  scope link  src 10.1.0.4
broadcast 127.0.0.0 dev lo  proto kernel  scope link  src 127.0.0.1
local 127.0.0.0/8 dev lo  proto kernel  scope host  src 127.0.0.1
local 127.0.0.1 dev lo  proto kernel  scope host  src 127.0.0.1
broadcast 127.255.255.255 dev lo  proto kernel  scope link  src 127.0.0.1
root@74c4feff-fbe2-4454-86af-530ba4413127:~# sudo service google-address-manager status
google-address-manager stop/waiting
root@74c4feff-fbe2-4454-86af-530ba4413127:~# sudo service google-address-manager start
google-address-manager start/running, process 7046
root@74c4feff-fbe2-4454-86af-530ba4413127:~# sudo service google-address-manager status
google-address-manager start/running, process 7046
root@74c4feff-fbe2-4454-86af-530ba4413127:~# ip route list table local
local 10.1.0.4 dev eth0  proto kernel  scope host  src 10.1.0.4
broadcast 10.1.0.4 dev eth0  proto kernel  scope link  src 10.1.0.4
broadcast 127.0.0.0 dev lo  proto kernel  scope link  src 127.0.0.1
local 127.0.0.0/8 dev lo  proto kernel  scope host  src 127.0.0.1
local 127.0.0.1 dev lo  proto kernel  scope host  src 127.0.0.1
broadcast 127.255.255.255 dev lo  proto kernel  scope link  src 127.0.0.1
local 130.211.186.50 dev eth0  proto 66  scope host
root@74c4feff-fbe2-4454-86af-530ba4413127:~#
```

Note the addition of the `130.211.186.50` route after starting it; that's our forwarding rule.

Stemcell version: `bosh-google-kvm-ubuntu-trusty-go_agent  3262.15*  ubuntu-trusty  stemcell-44d856f5-5749-41a3-7e30-252d9668c622`

BOSH/CPI versions:

```yaml
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.3
  sha1: e4442afcc64123e11f2b33cc2be799a0b59207d0
- name: bosh-google-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-google-cpi-release?v=24.4.0
  sha1: 2c13a452f76e27a101b287b61cc24851541aac18
- name: uaa
  url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=13
  sha1: 5229c6e8793c4061950b4e0738fc66612bc016ba
```

After starting the agent the VM became healthy and traffic started flowing again.
